name:                snail
version:             0.1.0.0
github:              "chiroptical/snail"
license:             MIT
author:              "Barry Moore"
maintainer:          "chiroptical@gmail.com"
copyright:           "Barry Moore II"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A programming language for gastropods

dependencies:
- base >= 4.15 && < 5
- containers >= 0.6.7 && < 0.7
- megaparsec >= 9.3.1 && < 9.4
- mtl >= 2.2.2 && < 2.3
- QuickCheck >= 2.14.3 && < 2.15
- text >= 2.0.2 && < 2.1
- text-display >= 0.0.5 && < 0.1

default-extensions:
- ImportQualifiedPost
- LambdaCase
- OverloadedStrings

library:
  source-dirs: src

tests:
  snail-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-discover
    - HUnit
    - raw-strings-qq
    - snail
