name:                snail
version:             0.1.2.1
github:              "chiroptical/snail"
license:             MIT
author:              "Barry Moore II"
maintainer:          "chiroptical@gmail.com"
copyright:           "Barry Moore II"
synopsis:            A programming language with no semantics
category:            Parsing
description:
  An s-expression parser and abstract syntax tree for a programming language
  with no semantics. If you wanted to write an interpreter or compiler you
  convert the AST into your own.

extra-source-files:
- README.md
- CHANGELOG.md

data-files:
- snail-files/*.snail
- test/files/*

dependencies:
- base >= 4.15 && < 5
- containers >= 0.6.7 && < 0.7
- megaparsec >= 9.3.1 && < 9.4
- mtl >= 2.2.2 && < 2.3
- QuickCheck >= 2.14.3 && < 2.15
- text >= 2.0.2 && < 2.1
- text-display >= 0.0.5 && < 0.1

default-extensions:
- FlexibleContexts
- ImportQualifiedPost
- LambdaCase
- OverloadedStrings
- TypeApplications

library:
  source-dirs: src

tests:
  snail-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snail
    - HUnit >= 1.6.2 && < 1.7
    - hspec >= 2.10.10 && < 2.11
    - hspec-discover >= 2.10.10 && < 2.11
    - raw-strings-qq >= 1.1 && < 1.2

executable:
  main: Main.hs
  source-dirs: example
  dependencies:
    - snail
